### PR TITLE
Test with more recent Java and Node versions

### PR DESCRIPTION
**Pull request by CedricGuillemet**

### CODE REVIEW

**Comment by matthargett** [comment]
landing RNTA updated to nodejs 18, so maybe this just needs a rebase?

**Comment by CedricGuillemet** [comment]
Got this build error with RN 0.64:
```
Script '/Users/runner/work/BabylonReactNative/BabylonReactNative/Apps/Playground/0.64/node_modules/react-native/react.gradle' line: 300

* What went wrong:
A problem occurred configuring project ':app'.
> Could not create task ':app:copyDebugBundledJs'.
   > Could not create task ':app:mergeDebugAssets'.
      > Cannot use @TaskAction annotation on method IncrementalTask.taskAction$gradle_core() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
```

RN 0.64 gradle build script is deprecated. `tasks.whenTaskAdded` must be replaced with `tasks.configureEach`. So, it's not possible to update Java until RN 0.64 is being used by the build.

**Comment by CedricGuillemet** [comment]
Another test using RN 0.69 instead of 0.64 for PR build and got this error with Windows build:
```
RNPermissions.vcxproj(160,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is D:\a\BabylonReactNative\BabylonReactNative\Apps\Playground\Playground\windows\\packages\Microsoft.Windows.CppWinRT.2.0.200316.3\build\native\Microsoft.Windows.CppWinRT.props.
```

This issue was fixed in RNPermissions when working on RNTA and RNPermissions@4.1.5 was released. 4.1.5 needs react@18.1.0 which makes it incompatible with RN 0.69 because of a dependency to react@18.0.0.

Envisaged solutions:
- use PR build to use Playground 0.70 or 0.71 and deprecate 0.69 as well
- use PR build to use Playground 0.70 or 0.71 but keep 0.69 (might see issues only when publishing)
- use RNTA

**Comment by tido64** [comment]
If I'm not mistaken, the reason you're seeing that error is because the `.vcxproj` has not been updated to use package references introduced in RNW 0.68. Removing the checks at the bottom of the project file (for reference, see https://github.com/zoontek/react-native-permissions/pull/860) should let you build and can be done with `patch-package`. It's another solution if you're fine with patching RNPermissions.

**Comment by CedricGuillemet** [comment]
Closing for https://github.com/BabylonJS/BabylonReactNative/pull/647

**Pull request closed without merging**
